import {
  Season,
  TimeOfDay,
} from '../../providers/greeting-context/greeting-context.service';

export type OccasionImageMap = Record<string, Record<TimeOfDay, string[]>>;

const img = (seed: string) => `https://picsum.photos/seed/${seed}/800/1200`;

export const SEASON_TIME_IMAGE_URLS: Record<
  Season,
  Record<TimeOfDay, string[]>
> = {
  spring: {
    morning: [
      img('blossom-sunrise'),
      img('meadow-dawn'),
      img('dew-flowers'),
      img('sunrise-petals'),
      img('spring-birch-morning'),
    ],
    afternoon: [
      img('spring-garden'),
      img('cherry-blossom'),
      img('flowers-blue-sky'),
      img('wildflowers-field'),
      img('spring-butterfly'),
    ],
    evening: [
      img('spring-sunset'),
      img('park-dusk'),
      img('tulips-evening'),
      img('lavender-sunset'),
      img('spring-dusk-pond'),
    ],
    night: [
      img('moonlit-garden'),
      img('night-blossoms'),
      img('stars-spring'),
      img('firefly-spring-night'),
      img('spring-crescent-moon'),
    ],
  },
  summer: {
    morning: [
      img('beach-sunrise'),
      img('summer-dawn'),
      img('golden-morning-sea'),
      img('sunrise-ocean'),
      img('summer-morning-mist'),
    ],
    afternoon: [
      img('sunny-beach'),
      img('summer-field'),
      img('blue-sea'),
      img('sunflower-field'),
      img('summer-pool'),
    ],
    evening: [
      img('beach-sunset'),
      img('summer-golden-hour'),
      img('sea-dusk'),
      img('tropical-sunset'),
      img('summer-evening-palms'),
    ],
    night: [
      img('summer-stars'),
      img('fireflies-night'),
      img('moonlit-sea'),
      img('milky-way-summer'),
      img('night-ocean-stars'),
    ],
  },
  autumn: {
    morning: [
      img('misty-autumn-forest'),
      img('autumn-dawn'),
      img('foggy-leaves'),
      img('autumn-mist-river'),
      img('fall-morning-light'),
    ],
    afternoon: [
      img('autumn-leaves'),
      img('golden-forest'),
      img('red-autumn-path'),
      img('maple-leaves-sun'),
      img('autumn-vineyard'),
    ],
    evening: [
      img('autumn-sunset'),
      img('orange-sky-trees'),
      img('cozy-autumn-dusk'),
      img('autumn-bonfire-dusk'),
      img('fall-evening-fog'),
    ],
    night: [
      img('harvest-moon'),
      img('dark-autumn-forest'),
      img('starry-autumn'),
      img('autumn-full-moon'),
      img('fall-night-lanterns'),
    ],
  },
  winter: {
    morning: [
      img('snowy-dawn'),
      img('frost-morning'),
      img('winter-sunrise'),
      img('blizzard-morning'),
      img('ice-crystals-dawn'),
    ],
    afternoon: [
      img('snowy-landscape'),
      img('winter-village'),
      img('snow-field'),
      img('frozen-lake'),
      img('winter-pine-forest'),
    ],
    evening: [
      img('cozy-fireplace'),
      img('candles-snow-window'),
      img('winter-dusk'),
      img('aurora-winter-eve'),
      img('snow-cabin-dusk'),
    ],
    night: [
      img('winter-stars'),
      img('moonlit-snow'),
      img('snow-night-forest'),
      img('northern-lights'),
      img('winter-full-moon'),
    ],
  },
};

export const OCCASION_IMAGE_URLS: OccasionImageMap = {
  new_year: {
    morning: [
      img('fireworks-dawn'),
      img('new-year-sunrise'),
      img('sparklers-morning'),
      img('new-year-morning-city'),
      img('champagne-sunrise'),
    ],
    afternoon: [
      img('new-year-celebration'),
      img('confetti-day'),
      img('champagne-day'),
      img('balloon-release-day'),
      img('new-year-parade'),
    ],
    evening: [
      img('fireworks'),
      img('sparklers'),
      img('new-year-city-lights'),
      img('new-year-lights-bridge'),
      img('fireworks-crowd'),
    ],
    night: [
      img('midnight-fireworks'),
      img('new-year-night'),
      img('countdown-night'),
      img('new-year-midnight-sky'),
      img('glitter-night'),
    ],
  },
  union_day: {
    morning: [
      img('romania-flag-sunrise'),
      img('tricolor-dawn'),
      img('union-morning'),
      img('alba-iulia-sunrise'),
      img('romanian-countryside-dawn'),
    ],
    afternoon: [
      img('romania-flag'),
      img('tricolor'),
      img('unity-monument'),
      img('alba-iulia'),
      img('tricolor-parade'),
    ],
    evening: [
      img('tricolor-sunset'),
      img('flag-dusk'),
      img('union-evening'),
      img('romania-sunset-mountains'),
      img('union-ceremony-dusk'),
    ],
    night: [
      img('tricolor-night'),
      img('monument-night'),
      img('union-night-lights'),
      img('romania-night-city'),
      img('tricolor-fireworks-night'),
    ],
  },
  easter: {
    morning: [
      img('easter-sunrise'),
      img('spring-church-dawn'),
      img('easter-eggs-morning'),
      img('easter-lily-sunrise'),
      img('church-bells-dawn'),
    ],
    afternoon: [
      img('easter-eggs'),
      img('spring-church'),
      img('white-lilies'),
      img('easter-basket'),
      img('painted-eggs-table'),
    ],
    evening: [
      img('church-candles-evening'),
      img('easter-sunset'),
      img('lilies-dusk'),
      img('orthodox-procession-dusk'),
      img('easter-glow-evening'),
    ],
    night: [
      img('candlelight-easter'),
      img('orthodox-night-service'),
      img('easter-candles'),
      img('church-midnight-service'),
      img('resurrection-candles-night'),
    ],
  },
  labour_day: {
    morning: [
      img('sunny-meadow-dawn'),
      img('spring-morning-park'),
      img('may-day-sunrise'),
      img('may-sunrise-park'),
      img('first-may-flowers-dawn'),
    ],
    afternoon: [
      img('sunny-meadow'),
      img('spring-picnic'),
      img('green-park'),
      img('spring-festival-day'),
      img('outdoor-barbecue'),
    ],
    evening: [
      img('park-sunset'),
      img('picnic-dusk'),
      img('meadow-evening'),
      img('park-gathering-dusk'),
      img('may-day-lights-evening'),
    ],
    night: [
      img('park-night'),
      img('spring-night-lights'),
      img('may-night'),
      img('may-night-city'),
      img('spring-festival-night'),
    ],
  },
  childrens_day: {
    morning: [
      img('playground-morning'),
      img('balloons-sunrise'),
      img('children-dawn'),
      img('kids-running-sunrise'),
      img('colorful-kites-morning'),
    ],
    afternoon: [
      img('playground'),
      img('colorful-balloons'),
      img('children-park'),
      img('carousel-afternoon'),
      img('ice-cream-park'),
    ],
    evening: [
      img('playground-sunset'),
      img('balloons-dusk'),
      img('children-evening'),
      img('fireworks-kids-dusk'),
      img('playground-golden-hour'),
    ],
    night: [
      img('night-fairground'),
      img('children-night-lights'),
      img('stars-children'),
      img('fairground-lights'),
      img('childrens-night-parade'),
    ],
  },
  assumption: {
    morning: [
      img('church-morning'),
      img('marigolds-sunrise'),
      img('assumption-dawn'),
      img('marigold-church-sunrise'),
      img('pilgrimage-dawn'),
    ],
    afternoon: [
      img('orthodox-church'),
      img('marigolds'),
      img('church-candles'),
      img('monastery-garden'),
      img('sunflowers-church'),
    ],
    evening: [
      img('church-sunset'),
      img('candles-dusk'),
      img('marigolds-evening'),
      img('monastery-candles-dusk'),
      img('marigold-sunset'),
    ],
    night: [
      img('church-candles-night'),
      img('orthodox-night'),
      img('candles-dark'),
      img('vigil-candles-night'),
      img('monastery-moonlit'),
    ],
  },
  saint_andrew: {
    morning: [
      img('autumn-monastery-dawn'),
      img('november-frost-morning'),
      img('mist-forest-morning'),
      img('garlic-wreath-dawn'),
      img('wolf-frost-morning'),
    ],
    afternoon: [
      img('autumn-monastery'),
      img('wolf-forest'),
      img('november-mist'),
      img('danube-delta-afternoon'),
      img('cave-saint-andrew'),
    ],
    evening: [
      img('monastery-sunset'),
      img('dark-forest-dusk'),
      img('november-evening'),
      img('october-mist-evening'),
      img('wolf-tracks-dusk'),
    ],
    night: [
      img('monastery-night'),
      img('forest-night-mist'),
      img('saint-andrew-night'),
      img('full-moon-wolves'),
      img('november-starry-forest'),
    ],
  },
  national_day: {
    morning: [
      img('winter-flag-sunrise'),
      img('snowy-dawn-flag'),
      img('december-morning'),
      img('carpathian-sunrise'),
      img('romania-dawn-village'),
    ],
    afternoon: [
      img('winter-flag'),
      img('snow-mountains'),
      img('december-village'),
      img('military-parade'),
      img('tricolor-sky'),
    ],
    evening: [
      img('flag-winter-sunset'),
      img('mountain-dusk-snow'),
      img('december-evening'),
      img('bucharest-lights-dusk'),
      img('december-ceremony-evening'),
    ],
    night: [
      img('winter-flag-night'),
      img('snowy-village-night'),
      img('december-night-lights'),
      img('bucharest-night-lights'),
      img('national-day-fireworks'),
    ],
  },
  saint_nicholas: {
    morning: [
      img('snow-gifts-morning'),
      img('winter-boots-sunrise'),
      img('nicholas-dawn'),
      img('christmas-boot-morning'),
      img('gift-sack-dawn'),
    ],
    afternoon: [
      img('snow-gifts'),
      img('winter-boots-snow'),
      img('snowy-afternoon'),
      img('toy-shop-snow'),
      img('children-gifts-day'),
    ],
    evening: [
      img('gifts-candlelight'),
      img('snowy-evening-boots'),
      img('nicholas-dusk'),
      img('candle-gifts-evening'),
      img('snow-lantern-dusk'),
    ],
    night: [
      img('snowy-night'),
      img('gifts-by-firelight'),
      img('nicholas-night'),
      img('gift-tree-night'),
      img('nicholas-starry-night'),
    ],
  },
  christmas: {
    morning: [
      img('christmas-tree-sunrise'),
      img('snow-lights-morning'),
      img('christmas-dawn'),
      img('nativity-sunrise'),
      img('carol-singers-dawn'),
    ],
    afternoon: [
      img('christmas-tree'),
      img('snow-lights'),
      img('winter-village-christmas'),
      img('christmas-market'),
      img('gifts-under-tree'),
    ],
    evening: [
      img('christmas-candles-evening'),
      img('snow-lights-dusk'),
      img('christmas-glow'),
      img('christmas-fireplace'),
      img('snow-village-lights'),
    ],
    night: [
      img('winter-candles'),
      img('christmas-night-lights'),
      img('christmas-starry-night'),
      img('christmas-stars-night'),
      img('silent-night-snow'),
    ],
  },
};
