import {
  Month,
  TimeOfDay,
} from '../../providers/greeting-context/greeting-context.service';

export type OccasionImageMap = Record<string, Record<TimeOfDay, string[]>>;

// picsum: deterministic random photo by seed (content unrelated to seed string)
const img = (seed: string) => `https://picsum.photos/seed/${seed}/800/1200`;

export const MONTH_TIME_IMAGE_URLS: Record<
  Month,
  Record<TimeOfDay, string[]>
> = {
  january: {
    morning: [
      img('winter sunrise,snow,frost'),
      img('frozen river,dawn,winter'),
      img('snow village,winter morning'),
      img('ice crystals,window,dawn'),
      img('snowy forest,sunrise,winter'),
    ],
    afternoon: [
      img('snowy landscape,bright,winter'),
      img('winter village,snow,daylight'),
      img('frozen lake,winter,sun'),
      img('snow field,blue sky,winter'),
      img('pine forest,snow,afternoon'),
    ],
    evening: [
      img('snow,winter sunset,orange sky'),
      img('cozy window,snow,dusk'),
      img('winter dusk,snowy village'),
      img('candles,snow,window,evening'),
      img('winter cabin,snow,golden hour'),
    ],
    night: [
      img('snow,moonlight,winter night'),
      img('winter stars,snowy forest'),
      img('frozen landscape,full moon,night'),
      img('snow,night sky,stars'),
      img('winter village,moonlit,snow'),
    ],
  },
  february: {
    morning: [
      img('snowdrop flowers,frost,dawn'),
      img('late winter,morning light,frost'),
      img('first spring signs,snow,sunrise'),
      img('snowdrops,melting snow,morning'),
      img('winter field,sunrise,cold'),
    ],
    afternoon: [
      img('snowdrops,bright,winter sun'),
      img('bare trees,sunlight,winter'),
      img('winter field,blue sky,snowdrops'),
      img('crocus,snow,bright afternoon'),
      img('late winter,countryside,sun'),
    ],
    evening: [
      img('snowdrops,winter sunset'),
      img('bare trees,dusk,winter'),
      img('late winter,golden hour,field'),
      img('winter evening,snow,sunset'),
      img('snowdrops,dusk,cold light'),
    ],
    night: [
      img('winter night,bare trees,moon'),
      img('snow,cold night,stars'),
      img('february,moonlight,frost'),
      img('bare trees,moonlit,winter night'),
      img('last winter snow,night,stars'),
    ],
  },
  march: {
    morning: [
      img('cherry blossom,sunrise,morning'),
      img('crocus flowers,morning dew,spring'),
      img('snowdrops,spring dawn,garden'),
      img('apple blossom,dawn,dew'),
      img('magnolia,sunrise,pink'),
    ],
    afternoon: [
      img('cherry blossom,blue sky,bright'),
      img('crocuses,colorful,spring sunshine'),
      img('orchard,blossoms,spring afternoon'),
      img('tulips,spring,garden'),
      img('wildflowers,meadow,march'),
    ],
    evening: [
      img('cherry blossom,sunset,pink sky'),
      img('spring flowers,golden hour'),
      img('orchard,blossoms,dusk'),
      img('tulips,spring,evening light'),
      img('spring,sunset,countryside'),
    ],
    night: [
      img('cherry blossom,night,moon'),
      img('spring garden,moonlight,flowers'),
      img('blossoms,stars,night sky'),
      img('magnolia,night,dark blue'),
      img('spring flowers,crescent moon'),
    ],
  },
  april: {
    morning: [
      img('apple blossom,sunrise,spring'),
      img('tulips,morning dew,dawn'),
      img('spring rain,morning,flowers'),
      img('cherry blossom,april,dawn'),
      img('orchard,peak bloom,sunrise'),
    ],
    afternoon: [
      img('tulips,bright,spring sunshine'),
      img('apple blossom,full bloom,blue sky'),
      img('spring wildflowers,meadow,bright'),
      img('cherry blossom,april,afternoon'),
      img('lilac,garden,spring'),
    ],
    evening: [
      img('tulips,golden hour,spring'),
      img('apple blossom,dusk,pink'),
      img('spring rain,sunset,rainbow'),
      img('orchard,evening,blossoms'),
      img('lilac,dusk,spring garden'),
    ],
    night: [
      img('spring garden,moonlight,april'),
      img('apple blossom,night,moon'),
      img('tulips,moonlit,dark'),
      img('spring night,stars,flowers'),
      img('cherry blossom,april night,sky'),
    ],
  },
  may: {
    morning: [
      img('peony flowers,sunrise,garden'),
      img('lilac,morning,spring'),
      img('green meadow,sunrise,may'),
      img('wildflowers,morning light,field'),
      img('rose bud,dawn,spring'),
    ],
    afternoon: [
      img('peony garden,bright,colorful'),
      img('lilac bush,sunlight,spring'),
      img('green meadow,wildflowers,sunshine'),
      img('may flowers,garden,bright'),
      img('countryside,green,spring afternoon'),
    ],
    evening: [
      img('peonies,sunset,garden'),
      img('lilac,golden hour,spring'),
      img('green meadow,evening,may'),
      img('wildflowers,dusk,warm light'),
      img('spring garden,evening,colorful'),
    ],
    night: [
      img('spring garden,moonlight,may night'),
      img('peonies,night,dark'),
      img('wildflowers,stars,night'),
      img('green countryside,moonlit,night'),
      img('may night,flowers,sky'),
    ],
  },
  june: {
    morning: [
      img('roses,sunrise,garden,summer'),
      img('summer morning,flowers,warm dawn'),
      img('rose garden,early morning,dew'),
      img('countryside,summer sunrise,green'),
      img('garden roses,sunrise,pink'),
    ],
    afternoon: [
      img('rose garden,summer,bright'),
      img('summer field,green,sunshine'),
      img('roses,june,afternoon,colorful'),
      img('summer meadow,bright,warm'),
      img('garden,flowers,summer afternoon'),
    ],
    evening: [
      img('roses,summer sunset,warm'),
      img('garden,summer evening,golden'),
      img('countryside,june,dusk'),
      img('rose,warm light,dusk'),
      img('summer garden,evening,flowers'),
    ],
    night: [
      img('summer night,garden,warm'),
      img('roses,moonlight,night'),
      img('june night,stars,garden'),
      img('warm summer night,flowers,sky'),
      img('fireflies,garden,summer night'),
    ],
  },
  july: {
    morning: [
      img('sunflower field,sunrise,morning'),
      img('lavender,morning light,summer'),
      img('summer dawn,countryside,warm'),
      img('sunflowers,golden morning,field'),
      img('lavender field,sunrise'),
    ],
    afternoon: [
      img('sunflower field,blue sky,bright'),
      img('lavender field,summer,sun'),
      img('hot summer day,countryside'),
      img('sunflowers,midday,yellow'),
      img('summer landscape,bright,warm'),
    ],
    evening: [
      img('sunflowers,sunset,golden hour'),
      img('lavender,dusk,purple sky'),
      img('summer countryside,golden hour'),
      img('sunflower field,evening,warm'),
      img('july sunset,countryside,warm'),
    ],
    night: [
      img('summer stars,milky way,night'),
      img('warm night,fireflies,field'),
      img('july night,countryside,stars'),
      img('sunflowers,moonlit,night'),
      img('summer night sky,stars,dark'),
    ],
  },
  august: {
    morning: [
      img('harvest field,sunrise,summer'),
      img('late summer dawn,countryside'),
      img('sunflowers,late summer,morning'),
      img('grain field,sunrise,august'),
      img('countryside,harvest,morning light'),
    ],
    afternoon: [
      img('harvest field,summer,bright'),
      img('sunflowers,late summer,afternoon'),
      img('countryside,august,warm'),
      img('wheat field,golden,afternoon'),
      img('late summer,blue sky,field'),
    ],
    evening: [
      img('harvest sunset,golden,summer'),
      img('late summer,dusk,countryside'),
      img('wheat field,golden hour,sunset'),
      img('sunflowers,august,evening'),
      img('rural,summer evening,warm'),
    ],
    night: [
      img('harvest moon,august,night'),
      img('summer night countryside,stars'),
      img('late summer,moonlit,field'),
      img('august night,stars,warm'),
      img('countryside,moonlight,summer night'),
    ],
  },
  september: {
    morning: [
      img('vineyard,sunrise,autumn,grapes'),
      img('autumn morning,golden,harvest'),
      img('september dawn,countryside,mist'),
      img('harvest field,misty morning,autumn'),
      img('golden morning,autumn,countryside'),
    ],
    afternoon: [
      img('vineyard,grapes,harvest,sunny'),
      img('autumn countryside,golden light'),
      img('september,warm afternoon,leaves'),
      img('harvest,village,autumn sun'),
      img('early autumn,colorful,countryside'),
    ],
    evening: [
      img('vineyard,sunset,golden autumn'),
      img('harvest golden hour,september'),
      img('autumn beginning,dusk,warm'),
      img('grapes,evening,september sunset'),
      img('countryside,early autumn,dusk'),
    ],
    night: [
      img('harvest moon,vineyard,night'),
      img('september stars,countryside'),
      img('autumn night,moonlit,village'),
      img('vineyard,night,moon'),
      img('early autumn,night sky,stars'),
    ],
  },
  october: {
    morning: [
      img('autumn forest,misty morning,colorful'),
      img('foggy autumn,dawn,leaves'),
      img('colorful autumn,sunrise,forest'),
      img('october morning,mist,trees'),
      img('autumn leaves,dew,morning light'),
    ],
    afternoon: [
      img('colorful autumn leaves,forest,bright'),
      img('golden autumn forest,october'),
      img('autumn village,leaves,sunshine'),
      img('red orange leaves,forest,afternoon'),
      img('october,countryside,autumn colors'),
    ],
    evening: [
      img('autumn sunset,colorful trees,orange'),
      img('october dusk,red leaves,sky'),
      img('misty autumn,evening,forest'),
      img('golden hour,autumn leaves,warm'),
      img('autumn forest,dusk,moody'),
    ],
    night: [
      img('full moon,autumn,orange'),
      img('dark autumn forest,night,october'),
      img('halloween moon,autumn,spooky'),
      img('october night,moonlit,leaves'),
      img('autumn night,stars,dark forest'),
    ],
  },
  november: {
    morning: [
      img('foggy morning,bare trees,november'),
      img('autumn mist,dawn,bare branches'),
      img('last leaves falling,morning,grey'),
      img('misty forest,november,dawn'),
      img('bare trees,fog,morning light'),
    ],
    afternoon: [
      img('bare trees,grey sky,november'),
      img('foggy countryside,autumn,late'),
      img('last autumn leaves,november'),
      img('misty village,november,afternoon'),
      img('dark clouds,bare trees,november'),
    ],
    evening: [
      img('bare trees,dusk,november'),
      img('foggy autumn,evening,dark'),
      img('november sunset,grey,moody'),
      img('misty evening,bare branches'),
      img('late autumn,dusk,village lights'),
    ],
    night: [
      img('bare trees,moonlight,november'),
      img('foggy night,november,dark'),
      img('november stars,bare trees,cold'),
      img('misty night,dark,november'),
      img('cold night,moon,bare branches'),
    ],
  },
  december: {
    morning: [
      img('first snow,winter sunrise,december'),
      img('frosty dawn,winter,christmas'),
      img('snowy village,morning,december'),
      img('winter sunrise,frost,christmas'),
      img('snow,dawn,december morning'),
    ],
    afternoon: [
      img('snowy village,december,winter'),
      img('christmas market,winter,afternoon'),
      img('snow landscape,winter,bright'),
      img('december,winter village,snow'),
      img('christmas lights,day,winter'),
    ],
    evening: [
      img('christmas lights,snow,dusk'),
      img('snowy village,december,evening'),
      img('candles,window,snow,christmas'),
      img('winter evening,festive lights'),
      img('christmas,snow,golden hour,village'),
    ],
    night: [
      img('christmas lights,snow,night'),
      img('snowy village,moonlit,december'),
      img('winter stars,snow,christmas night'),
      img('december night,festive,snow'),
      img('christmas,silent night,snow,moon'),
    ],
  },
};

export const OCCASION_IMAGE_URLS: OccasionImageMap = {
  new_year: {
    morning: [
      img('fireworks-dawn'),
      img('new-year-sunrise'),
      img('sparklers-morning'),
      img('new-year-morning-city'),
      img('champagne-sunrise'),
    ],
    afternoon: [
      img('new-year-celebration'),
      img('confetti-day'),
      img('champagne-day'),
      img('balloon-release-day'),
      img('new-year-parade'),
    ],
    evening: [
      img('fireworks'),
      img('sparklers'),
      img('new-year-city-lights'),
      img('new-year-lights-bridge'),
      img('fireworks-crowd'),
    ],
    night: [
      img('midnight-fireworks'),
      img('new-year-night'),
      img('countdown-night'),
      img('new-year-midnight-sky'),
      img('glitter-night'),
    ],
  },
  union_day: {
    morning: [
      img('romania-flag-sunrise'),
      img('tricolor-dawn'),
      img('union-morning'),
      img('alba-iulia-sunrise'),
      img('romanian-countryside-dawn'),
    ],
    afternoon: [
      img('romania-flag'),
      img('tricolor'),
      img('unity-monument'),
      img('alba-iulia'),
      img('tricolor-parade'),
    ],
    evening: [
      img('tricolor-sunset'),
      img('flag-dusk'),
      img('union-evening'),
      img('romania-sunset-mountains'),
      img('union-ceremony-dusk'),
    ],
    night: [
      img('tricolor-night'),
      img('monument-night'),
      img('union-night-lights'),
      img('romania-night-city'),
      img('tricolor-fireworks-night'),
    ],
  },
  easter: {
    morning: [
      img('easter-sunrise'),
      img('spring-church-dawn'),
      img('easter-eggs-morning'),
      img('easter-lily-sunrise'),
      img('church-bells-dawn'),
    ],
    afternoon: [
      img('easter-eggs'),
      img('spring-church'),
      img('white-lilies'),
      img('easter-basket'),
      img('painted-eggs-table'),
    ],
    evening: [
      img('church-candles-evening'),
      img('easter-sunset'),
      img('lilies-dusk'),
      img('orthodox-procession-dusk'),
      img('easter-glow-evening'),
    ],
    night: [
      img('candlelight-easter'),
      img('orthodox-night-service'),
      img('easter-candles'),
      img('church-midnight-service'),
      img('resurrection-candles-night'),
    ],
  },
  labour_day: {
    morning: [
      img('sunny-meadow-dawn'),
      img('spring-morning-park'),
      img('may-day-sunrise'),
      img('may-sunrise-park'),
      img('first-may-flowers-dawn'),
    ],
    afternoon: [
      img('sunny-meadow'),
      img('spring-picnic'),
      img('green-park'),
      img('spring-festival-day'),
      img('outdoor-barbecue'),
    ],
    evening: [
      img('park-sunset'),
      img('picnic-dusk'),
      img('meadow-evening'),
      img('park-gathering-dusk'),
      img('may-day-lights-evening'),
    ],
    night: [
      img('park-night'),
      img('spring-night-lights'),
      img('may-night'),
      img('may-night-city'),
      img('spring-festival-night'),
    ],
  },
  childrens_day: {
    morning: [
      img('playground-morning'),
      img('balloons-sunrise'),
      img('children-dawn'),
      img('kids-running-sunrise'),
      img('colorful-kites-morning'),
    ],
    afternoon: [
      img('playground'),
      img('colorful-balloons'),
      img('children-park'),
      img('carousel-afternoon'),
      img('ice-cream-park'),
    ],
    evening: [
      img('playground-sunset'),
      img('balloons-dusk'),
      img('children-evening'),
      img('fireworks-kids-dusk'),
      img('playground-golden-hour'),
    ],
    night: [
      img('night-fairground'),
      img('children-night-lights'),
      img('stars-children'),
      img('fairground-lights'),
      img('childrens-night-parade'),
    ],
  },
  assumption: {
    morning: [
      img('church-morning'),
      img('marigolds-sunrise'),
      img('assumption-dawn'),
      img('marigold-church-sunrise'),
      img('pilgrimage-dawn'),
    ],
    afternoon: [
      img('orthodox-church'),
      img('marigolds'),
      img('church-candles'),
      img('monastery-garden'),
      img('sunflowers-church'),
    ],
    evening: [
      img('church-sunset'),
      img('candles-dusk'),
      img('marigolds-evening'),
      img('monastery-candles-dusk'),
      img('marigold-sunset'),
    ],
    night: [
      img('church-candles-night'),
      img('orthodox-night'),
      img('candles-dark'),
      img('vigil-candles-night'),
      img('monastery-moonlit'),
    ],
  },
  saint_andrew: {
    morning: [
      img('autumn-monastery-dawn'),
      img('november-frost-morning'),
      img('mist-forest-morning'),
      img('garlic-wreath-dawn'),
      img('wolf-frost-morning'),
    ],
    afternoon: [
      img('autumn-monastery'),
      img('wolf-forest'),
      img('november-mist'),
      img('danube-delta-afternoon'),
      img('cave-saint-andrew'),
    ],
    evening: [
      img('monastery-sunset'),
      img('dark-forest-dusk'),
      img('november-evening'),
      img('october-mist-evening'),
      img('wolf-tracks-dusk'),
    ],
    night: [
      img('monastery-night'),
      img('forest-night-mist'),
      img('saint-andrew-night'),
      img('full-moon-wolves'),
      img('november-starry-forest'),
    ],
  },
  national_day: {
    morning: [
      img('winter-flag-sunrise'),
      img('snowy-dawn-flag'),
      img('december-morning'),
      img('carpathian-sunrise'),
      img('romania-dawn-village'),
    ],
    afternoon: [
      img('winter-flag'),
      img('snow-mountains'),
      img('december-village'),
      img('military-parade'),
      img('tricolor-sky'),
    ],
    evening: [
      img('flag-winter-sunset'),
      img('mountain-dusk-snow'),
      img('december-evening'),
      img('bucharest-lights-dusk'),
      img('december-ceremony-evening'),
    ],
    night: [
      img('winter-flag-night'),
      img('snowy-village-night'),
      img('december-night-lights'),
      img('bucharest-night-lights'),
      img('national-day-fireworks'),
    ],
  },
  saint_nicholas: {
    morning: [
      img('snow-gifts-morning'),
      img('winter-boots-sunrise'),
      img('nicholas-dawn'),
      img('christmas-boot-morning'),
      img('gift-sack-dawn'),
    ],
    afternoon: [
      img('snow-gifts'),
      img('winter-boots-snow'),
      img('snowy-afternoon'),
      img('toy-shop-snow'),
      img('children-gifts-day'),
    ],
    evening: [
      img('gifts-candlelight'),
      img('snowy-evening-boots'),
      img('nicholas-dusk'),
      img('candle-gifts-evening'),
      img('snow-lantern-dusk'),
    ],
    night: [
      img('snowy-night'),
      img('gifts-by-firelight'),
      img('nicholas-night'),
      img('gift-tree-night'),
      img('nicholas-starry-night'),
    ],
  },
  christmas: {
    morning: [
      img('christmas-tree-sunrise'),
      img('snow-lights-morning'),
      img('christmas-dawn'),
      img('nativity-sunrise'),
      img('carol-singers-dawn'),
    ],
    afternoon: [
      img('christmas-tree'),
      img('snow-lights'),
      img('winter-village-christmas'),
      img('christmas-market'),
      img('gifts-under-tree'),
    ],
    evening: [
      img('christmas-candles-evening'),
      img('snow-lights-dusk'),
      img('christmas-glow'),
      img('christmas-fireplace'),
      img('snow-village-lights'),
    ],
    night: [
      img('winter-candles'),
      img('christmas-night-lights'),
      img('christmas-starry-night'),
      img('christmas-stars-night'),
      img('silent-night-snow'),
    ],
  },
};
